adessoSE/budgeteer

- budgeteer-ubw-importer/build.gradle
- budgeteer-web-interface/build.gradle
- build.gradle
- make folder configuration for web interface module more versatile
(fixing error appearing when running gradlew idea before build
and creating configuration for generated sources folder)
- configure folders for ubw importer module
- enable annotation processing
(supersedes [pull request #105](https://github.com/thombergs/budgeteer/pull/105): done some cherry-picking to remove spurious commits and rollbacks)
> Corrections for IntelliJ configuration - fix initial build

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/imports/fileimport/ImportFilesPage.java
The import form gets refreshed every time the import format changes. See issue #116 for more details.
> Stopped form refresh in onUpdate (fixes #116)

- budgeteer-web-interface/build.gradle
- gradle.properties
The new spring boot version fixes the Gradle deprecation:
```
budgeteer-web-interface:bootRepackage
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
```
> updated spring boot version

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/user/login/LoginPage.java
One issue has been that Budgeteer wanted to use the FirstName and not the Username.
Therefore the Budgeteer couldn't create a new User or login with an existing User.
> Fixed keycloak login

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/budget/EditBudgetData.java
Fixed a bug that caused an exception when trying to add a tag to a budget at creation time.
This closes issue #191
> Fixed issue #191 - Tags can be added to new budgets

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/links/NetGrossLink.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/links/NetGrossLink.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/base/basepage/budgetunitchoice/BudgetUnitChoice.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/details/highlights/BudgetHighlightsPanel.java
An exception is not thrown anymore if the money display unit is changed on certain pages (#246).
Also fixed a few warnings related to getString() methods in object constructors (NetGrossLink and BudgetHighlightsPanel).
> [FIX-246] Exception was thrown when changing the money display unit and fixed a few warnings

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/instantiation/BudgeteerRequiresProjectListener.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/user/selectproject/SelectProjectPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/user/selectproject/SelectProjectPage.properties
- implemented #257 
- added new constructor to `SelectProjectPage`
- added new property to `SelectProjectPage.properties`
- `BudgeteerRequiresProjectListener` now redirects to `SelectProjectPage` with a error message
> [FIX-257] Show a error message when accessing pages without having a project selected

- budgeteer-web-interface/build.gradle
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/budget/BudgetEntity.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/budget/BudgetDetailData.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/budget/BudgetService.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/budget/EditBudgetData.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/details/BudgetDetailsPage.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/details/BudgetDetailsPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/notes/BudgetNotesPage.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/notes/BudgetNotesPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/notes/BudgetNotesPage.properties
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/notes/form/BudgetNotesForm.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/budget/BudgetServiceTest.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/web/pages/budgets/notes/BudgetNotesPageTest.java
- gradle.properties
Notes can be added to a budget using a WYSIQYG editor.
Maybe a version history could be added to keep track of who edited which note and when.
WYSIQYG editor is TinyMCE4 with [WicketStuff](https://github.com/wicketstuff/core/tree/master/tinymce4-parent).
> [FIX-28] Add functionality to write notes connected to budgets

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/templates/table/TemplatesTable.html
Fixed a typo found in the templates overview.
This fixes #289.
> [FIX-289]: typo in templates overview

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/base/basepage/BasePage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/details/BudgetDetailsPage.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/details/BudgetDetailsPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/overview/table/BudgetOverviewTable.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/budgetOverview/BudgetForContractOverviewPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/details/ContractDetailsPage.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/details/ContractDetailsPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/details/contractDetailChart/ContractDetailChart.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/details/highlights/ContractHighlightsPanel.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/details/InvoiceDetailsPage.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/details/InvoiceDetailsPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/details/highlights/InvoiceHighlightsPanel.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/edit/EditInvoicePage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/overview/InvoiceOverviewPage.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/overview/InvoiceOverviewPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/overview/table/InvoiceOverviewTable.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/user/selectproject/SelectProjectPage.java
- Fixed a bug that made the invoices page inaccessible when accesing it like this : `BudgetOverviewPage -> Contract (on any table entry) -> Show Invoices`
- Fixed a bug that caused an Exception when switching the Budget Display Unit or return from the SwitchProject menu : `ContractOverviewPage -> Contract Details -> Show Invoices` and  `BudgetOverviewPage -> Contract (on any table entry)`
- Fixed a bug that caused the user to always land on the Dashboard page (along with an exception) when returning from the Select/Switch Project page (on some pages, such as those with id's in their parameters).
- Fixed the URLs for the EditInvoicePage
- Adjusted the styling of the ContractDetailsPage (made the chart and table full-width, this should make them more readable) and InvoiceDetailsPage as it …
> [FIX-275] Fixed broken URLs and styling in some pages

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/record/WorkRecordFilter.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/burntable/BurnTableWithFilter.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/burntable/filter/FilterPanel.html
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/burntable/filter/FilterPanel.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/links/ResetFilterLink.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/hours/BudgetHoursPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/hours/HoursPage.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/person/hours/PersonHoursPage.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/web/components/burntable/BurnTableWithFilterTest.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/web/components/burntable/FilterPanelTest.java
Hours Pages (hours of all budget and persons, hours of one selected budget, hours of one selected person):
A button to reset the applied filters is added.
By clicking the button all filters are reseted to their default state.
This fixes #290.
> [FIX-290] added button for reseting filters to hours pages

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/person/PersonBaseDataBean.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/person/PersonDetailDataBean.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/person/PersonRepository.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/person/PersonServiceTest.java
This can happen with cancellation bookings. Anyway, a fatal database error should be prevented any time.
In this case now the weighted minutes default to a zero rate (to give a simple value).
fixes #292
> save person repository from db error when work records sum to zero

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/burntable/table/BurnTable.java
- When editing an item and saving, the user will now automatically land on the page the item was transferred to. 
For example when sorting by Daily Rates records might change their location on the pages.
- The total burned budget with current filter value is updated immediately after saving the edited rate.
> Minor improvements to the hours page

- budgeteer-resourceplan-importer/src/main/java/org/wickedsource/budgeteer/importer/resourceplan/ResourcePlanImporter.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/record/PlanRecordRepository.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/imports/PlanRecordDatabaseImporter.java
This PR fixes #267. 
Previously, when importing plan records, all old records of the whole project before the earliest date of the imported records  were deleted.
This caused deletion of records of budgets, which weren't included in the import.
Now only the old records of budgets which are contained in the imported records are deleted.
> [FIX-267] Fix deletion of plan records at import

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/budget/report/BudgetReportService.java
When creating a budget report, the formulas from the template were evaluated by Apache POI, causing formulas to throw an exception without the support of the framework.
The evaluation is not necessary, because Excel evaluates the formulas when opening the file. That's why we deleted the evaluation by Apache POI.
Fixes #410
> budgetReport: Deletes formula evaluation by apache poi

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/contract/ContractFieldEntity.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/contract/ContractService.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/contract/ContractServiceTest.java
This also includes a cleanup of the code. Instead of iterating trough
the lists with a nested for-loop, we now create a map with the field
name as a key. This allows us to quickly check if an attribute already
exists, and update it, or create a new one.
EDIT: I have updated the PR so that the order of attributes is guaranteed.
Closes #395
> contract: Allow empty values for additional information fields

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/record/AggregatedRecord.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/record/RecordJoiner.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/record/RecordJoinerTest.java
Before the weekly budget overview only showed the week number
("Week #%d"), with made it hard to distinguish from which month each
record was. Now we prepend the year to the week ("Week %d-%d"). The
format of the monthly overview was changed to be the same
("Month %d/%02d" to "Month %d-%02d").
This also fixes sorting by aggregation period in the monthly overview,
as it now sorts my year and week, instead of just week.
Closes #175
> budget: Change format of aggregation period in budget overview

- budgeteer-report-exporter/src/main/java/org/wickedsource/budgeteer/SheetTemplate/SheetTemplateSerializable.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/budget/report/BudgetReportService.java
This pull request addresses issue #427.
The null pointer exception occurs because calling _getValue_ can return null. Calling _toString_ on a null value will result in an NPE.
That's why the check is needed if the value isn't null. After this we can safely call toString.
Closes #427
> budget: Filter null values out of budget attributes

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/person/PersonDetailDataBean.java
When accessing the details page for a person after all their records
have been deleted a NullPointerException was triggered because the query
in PersonRepository#findDetailDataByPersonId fed the
PersonDetailDataBean constructor null values for valuedMinutes, and
valuedRate, since the table it joins with is empty. As a workaround we
do what is already done in the PersonBaseDataBean constructor. We check
if valuedMinutes is null and, if it is null, default
averageDailyRateInCents to 0.
Fixes #422
> person: Fix error when accessing a person details when no records exist

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/person/PersonRate.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/person/PersonService.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/person/edit/personrateform/EditPersonForm.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/person/PersonServiceIntegrationTest.java
As described in the issue this pull request introduces security for null values. Furthermore incorrect DailyRates are no longer saved in the PersonEntity.
This solution provides a current solution. In the future such logics should be mapped in a service for the repository.
Closes #426
> person: Add null safety to update daily rates

- budgeteer-report-exporter/src/main/java/org/wickedsource/budgeteer/SheetTemplate/SheetTemplateSerializable.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/budget/report/BudgetReportService.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/contract/report/ContractReportService.java
This pull request addresses issue #442.
The null pointer exception occurs because calling getValue can return null. Calling toString on a null value will result in an NPE.
That's why the check is needed if the value isn't null. After this we can safely call toString.
**This pull request is based on #435. Before merging this pull request a rebase should be performed.**
Closes #442
> contract: Filter null values out of contract attributes

- budgeteer-app/src/test/java/de/adesso/budgeteer/BudgeteerApplicationTest.java
- budgeteer-app/src/test/resources/application-test.yml
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/user/UserAdapter.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/user/UserMapper.java
We previously forgot to implement GetAuthenticationUserPort. This caused
the application to no longer start. To help prevent such errors in the
future, a simple test to load the application context was added.
> persistence: Implement the missing GetAuthenticationUserPort

- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/BudgeteerMethodSecurityExpressionHandler.java
- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/BudgeteerMethodSecurityExpressionRoot.java
- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/MethodSecurityConfig.java
This allows us to use expression based method security to secure the REST API.
See the [Spring Docs](https://docs.spring.io/spring-security/site/docs/5.0.7.RELEASE/reference/html/el-access.html) for more details on how to use it.
> security: Provide setup for expression based method security

- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/json/MoneyJsonDeserializer.java
- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/json/MoneyJsonSerializer.java
- budgeteer-rest/src/test/java/de/adesso/budgeteer/rest/json/MoneyJsonTest.java
Jackson doesn't offer proper serialization/deserialization of the joda-money Money type. So we have to do it ourselves.
> json: Add custom serialization/deserialization of Money

- budgeteer-core/src/main/java/de/adesso/budgeteer/core/user/service/RegisterService.java
- budgeteer-core/src/test/java/de/adesso/budgeteer/core/user/service/RegisterServiceTest.java
In the past we used SHA512 to hash password. Since then we switched to BCrypt, but didn't remove the hashing from the RegisterService.
This caused accounts to be unable to log in, since the password was now unusable.
> user: Fix RegisterService hashing the already hashed password

- budgeteer-core/src/main/java/de/adesso/budgeteer/core/project/port/in/UserHasAccessToProjectUseCase.java
- budgeteer-core/src/main/java/de/adesso/budgeteer/core/project/port/out/UserHasAccessToProjectPort.java
- budgeteer-core/src/main/java/de/adesso/budgeteer/core/project/service/UserHasAccessToProjectService.java
- budgeteer-core/src/test/java/de/adesso/budgeteer/core/project/service/UserHasAccessToProjectServiceTest.java
- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/project/ProjectController.java
- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/BudgeteerMethodSecurityExpressionHandler.java
- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/BudgeteerMethodSecurityExpressionRoot.java
- budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/MethodSecurityConfig.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/project/ProjectAdapter.java
- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/project/ProjectRepository.java
- budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/persistence/project/ProjectRepositoryTest.java
This adds the `userHasAccessToProject(String username, long projectId)` method to the security expression root, and uses it to further secure the endpoint `/projects/{projectId}`.
When a user doesn't have access to the project the user will receive a `403 Forbidden` status code. Otherwise they will get the requested project.
I used the username, instead of the id like usual, since using the username is easier as you can directly pass it to the expression.
> Project authorization via method security expression

- .github/workflows/build.yml
Spotless requires a valid branch name, even if it isn't run. This ensures that the `MAIN_BRANCH` variable is only set when building a pull request. This causes the build script to fall back to `main` which should always be available when building `main`.
> Fix main branch not building due to spotless

- build.gradle
When adding JaCoCo we forgot to enable the generation of reports after tests.
Enabling them allows SonarQube to show proper coverage information.
> Generate JaCoCo test reports

- .github/workflows/docker-nightly.yaml
The `outputs` of the `check-commit-dates` job read the output of `steps.should_run.outputs.should_run`, which doesn't exist, instead of `steps.check-commit-dates.outputs.should-run`. 
This caused nightly builds not to run, since `needs.check-commit-dates.outputs.should-run` was always false.
> ci: Fix a typo in the output of the check-commit-dates job

- budgeteer-persistence/src/main/java/de/adesso/budgeteer/persistence/invoice/InvoiceEntityAdapter.java
- budgeteer-persistence/src/test/java/de/adesso/budgeteer/persistence/invoice/InvoiceEntityAdapterTest.java
A NullPointerException was thrown by
InvoiceEntityAdapter#createInvoiceEntity() when attributes was null due
to a missing check to see if attributes were set.
> invoice: Fix NPE when attributes is null in CreateInvoiceModel

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/edit/form/EditContractForm.java
A `RuntimeException` was thrown when editing the additional attributes on contracts because a setter for `DynamicAttributeField` wasn't provided.
Fixes #533
> contract: Fix RuntimeException when editing additional attributes

- budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/BudgeteerSession.java
This issue seems to have been caused by calling `replaceSession()` after
`invalidate()` in `logout()`. Since it doesn't make sense to replace the
session after it was invalidated we just remove that call.
Closes #546
> login: Fix IllegalStateException after relogin
