adessoSE/budgeteer

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/project/ProjectService.java
Deleting a project without having a favourite project doesn't produce a NPE anymore (fixes #102)
=> Fix for Issue#102 

budgeteer-web-interface/build.gradle, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/boot/BudgeteerBooter.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/boot/WarInitializer.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/boot/WebInitializer.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/user/UserEntity.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/record/RecordService.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/record/WorkRecordQueries.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/IntegrationTestConfiguration.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/IntegrationTestTemplate.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/persistence/budget/BudgetRepositoryTest.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/record/RecordServiceTest.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/record/WorkRecordQueriesIntegrationTest.java, budgeteer-web-interface/src/test/resources/spring-repository-mock.xml, budgeteer-web-interface/src/test/resources/spring-service-mock.xml, budgeteer-web-interface/src/test/resources/spring-service.xml, budgeteer-web-interface/src/test/resources/spring-web.xml, build.gradle, gradle.d/idea.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
updated spring boot and made all necessary migrations regarding hibernate, spring context, etc.
=> spring boot update

budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/IntegrationTestTemplate.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/ServiceTestTemplate.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/contract/ContractServiceTest.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/imports/PlanRecordImporterTest.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/imports/WorkRecordImporterTest.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/invoice/InvoiceServiceTest.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/project/ProjectServiceTestWithDBUnit.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/web/AbstractWebTestTemplate.java, build.gradle, gradle.properties
fixed problem with mockito. updated to new Spring 4.3.x SpringRunner
=> fixed problem with mockito. updated to new Spring 4.3.x SpringRunner

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/edit/EditBudgetPage.properties, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/budgetOverview/BudgetForContractOverviewPage.properties, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/details/highlights/ContractHighlightsPanel.properties, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/imports/fileimport/ImportFilesPage.properties, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/details/InvoiceDetailsPage.properties, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/edit/EditInvoicePage.properties, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/person/edit/EditPersonPage.properties, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/user/selectproject/SelectProjectPage.properties
Unified syntax by deleting dots at the end of sentence.
=> Corrected typos, unified syntax

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/details/BudgetDetailsPage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/overview/BudgetsOverviewPage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/details/ContractDetailsPage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/overview/ContractOverviewPage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/dashboard/DashboardPage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/invoice/overview/InvoiceOverviewPage.html
unified all icons so that they are recognizable
=> Unified icons in boxes

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/base/basepage/BasePage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/base/basepage/BasePage.java
Added a link to the "SelectProjectPage" from the basepage.
=> Added "change project" functionality (fixes #114)

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/administration/ProjectAdministrationPage.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/dashboard/DashboardPage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/dashboard/DashboardPage.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/dashboard/ProjectnameModel.java
See the projectname in the "Welcome [username]... " sentence.
=> print the currently selected project to dashboard (fixes #128)

circle.yml, gradle.d/01-helper.gradle
=> caching dependencies in dependencies phase

.gitignore
excluded Mac OS X files
excluded all IntelliJ project files no matter what name
excluded binary files except gradle wrapper
=> modified ignore patterns

budgeteer-web-interface/src/main/resources/public/error/403.html, budgeteer-web-interface/src/main/resources/public/error/404.html, budgeteer-web-interface/src/main/resources/public/error/500.html
This could fix #160 in case these two error pages are the only ones budgeteer needs.
=> add error page for 404 and 403

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/edit/EditBudgetPage.properties, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/contract/edit/EditContractPage.properties
=> Renamed the Budget Total and Budget form labels in the Budget and Contract forms

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/dataTable/DataTableBehavior.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/components/money/MoneyConverter.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/overview/BudgetsOverviewPage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/overview/table/BudgetOverviewTable.html
=> Fixed the sorting of money in the tables

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/BudgeteerApplication.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/base/basepage/BasePage.html, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/base/basepage/BasePage.java
Integrity checks added for external CDN.
Look [here](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) for more information.
=> [FIX-182] Remove links to external dependencies

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/template/TemplateEntity.java
Fix from @tinne for issue #328
=> Аpplied patch to the template entity that fixes the copying of the workbook

budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/IntegrationTestConfiguration.java
=> [FIX-340] Added exclusion for FlywayAutoConfiguration

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/overview/table/BudgetOverviewTable.java
=> Fixed remaining budget filter

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/BudgeteerSession.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/edit/form/EditBudgetForm.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/budgets/overview/BudgetsOverviewPage.java
This PR fixes #353.
I could reproduce the bug mentioned in #353.
It seems to be caused by a NullPointerException. I fixed this by checking for a null value in the affected object.
After that, the exception didn't occur again.
=> [Fix-353] Fixed NullPointerException in Edit Budget Details

budgeteer-ubw-importer/src/main/java/org/wickedsource/budgeteer/importer/ubw/UBWWorkRecordsImporter.java, budgeteer-ubw-importer/src/test/java/org/wickedsource/budgeteer/importer/ubw/UBWWorkRecordsImporterTest.java, budgeteer-web-interface/src/main/resources/application.properties, build.gradle
This PR fixes the Importer. The proper sheet is found using the column names.
=> UBW Importer fix

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/imports/RecordDatabaseImporter.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/service/imports/WorkRecordDatabaseImporter.java
=> In case a work record gets ignored, do not accidentally create its budget

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/monitoring/StatusPage.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/monitoring/StatusPage.txt, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/monitoring/VersionPage.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/monitoring/VersionPage.txt
Add a page to display the current server version and show it is alive and kicking.
=> add simple version page

budgeteer-core/src/main/java/de/adesso/budgeteer/core/security/domain/AuthenticationUser.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/security/port/in/GetAuthenticationUserUseCase.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/security/port/out/GetAuthenticationUserPort.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/security/service/GetAuthenticationUserService.java, budgeteer-rest/build.gradle, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/SecurityConfig.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/jwt/JwtAuthorizationFilter.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/jwt/JwtUtil.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/jwt/configuration/JwtConfiguration.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/jwt/configuration/JwtProperties.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/userdetails/UserDetailsImpl.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/userdetails/UserDetailsMapper.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/userdetails/UserDetailsServiceImpl.java
This provides basic authorization and authentication via a JWT.
=> Rest JWTsecurity setup

budgeteer-core/src/test/java/de/adesso/budgeteer/core/project/service/UpdateDefaultProjectServiceTest.java, budgeteer-web-interface/src/test/java/org/wickedsource/budgeteer/service/user/UserServiceTest.java
The `UpdateDefaultProjectServiceTest` tests were broken because I forgot to change them, when I changed the API.
Some of the `UserServiceTest` tests were broken because we added `@Repository` to our repositories. I don't exactly know why that happened. Probably had something to do with the tests not being proper unit tests and loading some of the Spring context.
Anyway they are now proper unit tests, which fixes the issue.
=> Fix broken UpdateDefaultProjectServiceTest and UserServiceTest tests

budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/project/ProjectController.java
=> Clean architecture rest project Controller fix

budgeteer-core/src/main/java/de/adesso/budgeteer/core/budget/port/in/UserHasAccessToBudgetUseCase.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/budget/port/out/UserHasAccessToBudgetPort.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/budget/service/UserHasAccessToBudgetService.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/contract/port/in/UserHasAccessToContractUseCase.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/contract/port/out/UserHasAccessToContractPort.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/contract/service/UserHasAccessToContractService.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/invoice/port/in/UserHasAccessToInvoiceUseCase.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/invoice/port/out/UserHasAccessToInvoicePort.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/invoice/service/UserHasAccessToInvoiceService.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/person/port/in/UserHasAccessToPersonUseCase.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/person/port/out/UserHasAccessToPersonPort.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/person/service/UserHasAccessToPersonService.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/budget/BudgetController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/contract/ContractController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/invoice/InvoiceController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/person/PersonController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/project/ProjectController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/BudgeteerMethodSecurityExpressionHandler.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/BudgeteerMethodSecurityExpressionRoot.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/MethodSecurityConfig.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/budget/BudgetAdapter.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/contract/ContractAdapter.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/invoice/InvoiceEntityAdapter.java, budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/persistence/person/PersonEntityAdapter.java
Rebase of #501 because GitHub creates bad merges when resolving conflicts
=> Clean architecture rest method security

budgeteer-rest/build.gradle, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/budget/BudgetController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/budget/model/BudgetIdModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/budget/model/CreateBudgetModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/contract/ContractController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/contract/model/ContractIdModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/contract/model/CreateContractModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/invoice/InvoiceController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/invoice/model/CreateInvoiceModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/invoice/model/InvoiceIdModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/invoice/model/UpdateInvoiceModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/person/PersonController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/person/model/CreatePersonModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/person/model/PersonIdModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/project/ProjectController.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/project/model/ProjectIdModel.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/AspectConfig.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/HasAccessToBudgetAspect.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/HasAccessToContractAspect.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/HasAccessToInvoiceAspect.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/HasAccessToPersonAspect.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/HasAccessToProjectAspect.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/annotations/HasAccessToBudget.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/annotations/HasAccessToContract.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/annotations/HasAccessToInvoice.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/annotations/HasAccessToPerson.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/aspects/annotations/HasAccessToProject.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/security/authorization/methodsecurity/BudgeteerMethodSecurityExpressionRoot.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/user/model/UserIdModel.java
This replaces the `@MethodSecurity` on endpoints with a controller wide `@HasAccessTo*` annotation.
Closes #510
=> Method security via custom aspects

budgeteer-core/src/main/java/de/adesso/budgeteer/core/budget/port/in/GetBudgetsInContractUseCase.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/budget/port/out/GetBudgetsInContractPort.java, budgeteer-core/src/main/java/de/adesso/budgeteer/core/budget/service/GetBudgetsInContractService.java, budgeteer-core/src/test/java/de/adesso/budgeteer/core/budget/service/GetBudgetsInContractServiceTest.java, budgeteer-persistence/src/main/java/de/adesso/budgeteer/persistence/budget/BudgetAdapter.java, budgeteer-rest/src/main/java/de/adesso/budgeteer/rest/budget/BudgetController.java
=> Implemented rest api method to get all budgets in a contract

budgeteer-web-interface/src/main/java/org/wickedsource/budgeteer/web/pages/base/basepage/BasePage.java
I don't know why it was hidden in the first place, but everybody with
access to the project should be able to see the button, since they can
just adjust the URL anyway.
Closes #545
=> administration: Make administer project button visible

budgeteer-ubw-importer/build.gradle, budgeteer-ubw-importer/src/main/java/org/wickedsource/budgeteer/importer/ubw/UBWWorkRecordsImporter.java
The UBW importer would throw exceptions if more columns than expected were present and the cells in those columns were null.
=> ubw-importer: Fix issue when more columns than expected were present
